- hosts: db
  become: true
  roles:
    - { role: roles/nginx, when: enable_nginx_lb and load_balancer_is_required }
    - { role: roles/apache, when: enable_apache_lb and load_balancer_is_required }
    - { role: roles/mysql, when: enable_mysql_lb and load_balancer_is_required }