---
- name: Update apt cache.
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Apache is installed on Debian.
  become: true
  apt: "name={{ apache_packages }} state={{ apache_packages_state }}"
