---
- hosts: all
  become: true
  name: Include Dynamic Variables
  tasks:
    - include_playbook: ../static-assignments/common.yml
    - include_playbook: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

